
--/*
USE FARMATICA;

--* : Significa cambio con respecto al modelo anterior.

CREATE TABLE CLIENTE(
	IdCliente INT,				 -- *
	Cedula VARCHAR(11),
	Nombre VARCHAR (15),
	Apellido VARCHAR(15),
	Prioridad CHAR(1),
	FechaNacimiento DATE,
	Residencia VARCHAR(45),

	CONSTRAINT PK_CLIENTE
		PRIMARY KEY (IdCliente)
)

CREATE TABLE PADECIMIENTOS_POR_CLIENTE(
	IdCliente INT,
	Descripcion VARCHAR (100),
	
	CONSTRAINT FK_PADECIMIENTOS_POR_CLIENTE_IdCliente
		FOREIGN KEY (IdCliente) REFERENCES CLIENTE(IdCliente)
)


CREATE TABLE TELEFONOS_POR_CLIENTE(
	IdCliente INT,
	Telefono VARCHAR (11),
	Descripcion VARCHAR (20),

	CONSTRAINT PK_TELEFONOS_POR_CLIENTE
		PRIMARY KEY (IdCliente, Telefono),

	CONSTRAINT FK_TELEFONOS_POR_CLIENTE_IdCliente
		FOREIGN KEY (IdCliente) REFERENCES CLIENTE(IdCliente)
)

CREATE TABLE DOCTOR(
	NoDoctor INT,
	Cedula VARCHAR(15),
	Nombre VARCHAR(15),
	Apellido VARCHAR(15),
	FechaNacimiento DATE,
	Residencia VARCHAR(100),

	CONSTRAINT PK_DOCTOR 
		PRIMARY KEY (NoDoctor)	
)

CREATE TABLE RECETA(
	NoReceta INT,
	Imagen IMAGE,

	CONSTRAINT PK_RECETA
		PRIMARY KEY (NoReceta)
)



CREATE TABLE MEDICAMENTO(
	Prescipcion BIT,
	Codido INT,
	Nombre VARCHAR (15),
	Costo INT,

	CONSTRAINT PK_MEDICAMENTO
		PRIMARY KEY (Codido)
)

CREATE TABLE CASA_FARMACEUTICA(
	Identificador INT,
	Nombre VARCHAR(15),

	CONSTRAINT PK_CASA_FARMACEUTICA
		PRIMARY KEY (Identificador)
)

CREATE TABLE PEDIDO (
	HoraRecojo TIME(0),
	NoFactura INT,
	Telefono VARCHAR(8),		--*
	Estado VARCHAR(7),

	CONSTRAINT PK_PEDIDO
		PRIMARY KEY (NoFactura)
)


CREATE TABLE SUCURSAL (
	NoSucursal INT,
	Nombre VARCHAR (15),
	Direccion VARCHAR (100),

	CONSTRAINT PK_SUCURSAL
		PRIMARY KEY (NoSucursal)
)

CREATE TABLE MEDICAMENTOS_POR_RECETA(
	CodigoMedicamento INT,
	NoReceta INT,

	CONSTRAINT PK_MEDICAMENTOS_POR_RECETA
		PRIMARY KEY (CodigoMedicamento, NoReceta),

	CONSTRAINT FK_MEDICAMENTOS_POR_RECETA_CodigoMedicamento 
		FOREIGN KEY (CodigoMedicamento) REFERENCES MEDICAMENTO(Codido),

	CONSTRAINT FK_MEDICAMENTOS_POR_RECETA_NoReceta
		FOREIGN KEY (NoReceta) REFERENCES RECETA(NoReceta)
)

CREATE TABLE MEDICAMENTOS_POR_CASA_FARMACEUTICA(
	CodigoMedicamento INT,
	Identificador_Casa INT,

	CONSTRAINT PK_MEDICAMENTOS_POR_CASA_FARMACEUTICA
		PRIMARY KEY (CodigoMedicamento, Identificador_Casa),

	CONSTRAINT FK_MEDICAMENTOS_POR_CASA_FARMACEUTICA_CodigoMedicamento
		FOREIGN KEY (CodigoMedicamento) REFERENCES MEDICAMENTO(Codido),

	CONSTRAINT FK_MEDICAMENTOS_POR_CASA_FARMACEUTICA_Identificador_Casa
		FOREIGN KEY (Identificador_Casa) REFERENCES CASA_FARMACEUTICA(Identificador)
)

CREATE TABLE MEDICAMENTOS_SE_ENCUENTRA_EN_SUCURAL(
		CodigoMedicamento INT,
		NoSucursal INT,
		Cantidad INT,
		
		CONSTRAINT PK_MEDICAMENTOS_SE_ENCUENTRA_EN_SUCURAL
			PRIMARY KEY (CodigoMedicamento, NoSucursal),

		CONSTRAINT FK_MEDICAMENTOS_SE_ENCUENTRA_EN_SUCURAL_CodigoMedicamento
			FOREIGN KEY (CodigoMedicamento) REFERENCES MEDICAMENTO(Codido),

		CONSTRAINT FK_MEDICAMENTOS_SE_ENCUENTRA_EN_SUCURAL_NoSucursal
			FOREIGN KEY (NoSucursal) REFERENCES SUCURSAL(NoSucursal)
)

CREATE TABLE MEDICAMENTOS_POR_PEDIDO (
	NoFactura INT,
	CodigoMedicamento INT,

	CONSTRAINT PK_MEDICAMENTOS_POR_PEDIDO
		PRIMARY KEY (NoFactura, CodigoMedicamento),
	
	CONSTRAINT FK_MEDICAMENTOS_POR_PEDIDO_CodigoMedicamento
		FOREIGN KEY (CodigoMedicamento) REFERENCES MEDICAMENTO(Codido),

 	CONSTRAINT FK_MEDICAMENTOS_POR_PEDIDO_PEDIDO
		FOREIGN KEY (NoFactura) REFERENCES PEDIDO(NoFactura)
)


CREATE TABLE PEDIDOS_POR_CLIENTE(
	NoFactura INT,
	IdCliente INT,

	CONSTRAINT PK_PEDIDOS_POR_CLIENTE
		PRIMARY KEY (NoFactura, IdCliente),

 	CONSTRAINT FK_PEDIDOS_POR_CLIENTE_PEDIDO
		FOREIGN KEY (NoFactura) REFERENCES PEDIDO(NoFactura),

	CONSTRAINT FK_PEDIDOS_POR_CLIENTE_IdCliente
		FOREIGN KEY (IdCliente) REFERENCES CLIENTE(IdCliente)
)

CREATE TABLE PEDIDO_POR_SUCURSAL(
	NoFactura INT,
	NoSucursal INT,

	CONSTRAINT PK_PEDIDO_SE_RECOGE_EN_SUCURSAL
		PRIMARY KEY (NoFactura, NoSucursal),

 	CONSTRAINT FK_PEDIDO_SE_RECOGE_EN_SUCURSAL_NoFactura
		FOREIGN KEY (NoFactura) REFERENCES PEDIDO(NoFactura),

 	CONSTRAINT FK_PEDIDO_SE_RECOGE_EN_SUCURSAL_NoSucursal
		FOREIGN KEY (NoSucursal) REFERENCES SUCURSAL(NoSucursal)
)


CREATE TABLE TELEFONOS_POR_SUCURSALES(
	NoSucursal INT,
	Telefono VARCHAR(10),
	Descripcion VARCHAR(20),

	CONSTRAINT PK_TELEFONOS_POR_SUCURSALES
		PRIMARY KEY (NoSucursal,Telefono),

	CONSTRAINT FK_TELEFONOS_POR_SUCURSALES_NoSucursal
		FOREIGN KEY (NoSucursal) REFERENCES SUCURSAL(NoSucursal)
)

CREATE TABLE RECETAS_POR_PEDIDO(
	NoFactura INT,
	NoReceta INT,

	CONSTRAINT PK_RECETAS_POR_PEDIDO
		PRIMARY KEY (NoFactura, NoReceta),

	CONSTRAINT FK_RECETAS_POR_PEDIDO_NoFactura
		FOREIGN KEY (NoFactura) REFERENCES PEDIDO(NoFactura),

	CONSTRAINT FK_RECETAS_POR_PEDIDO_NoReceta
		FOREIGN KEY (NoReceta) REFERENCES RECETA(NoReceta)
)

CREATE TABLE RECETAS_POR_CLIENTE(
	NoReceta INT,
	IdCliente INT,

	
	CONSTRAINT PK_RECETAS_CLIENTE
		PRIMARY KEY (NoReceta, IdCliente),

	CONSTRAINT FK_RECETAS_POR_CLIENTE_NoReceta
		FOREIGN KEY (NoReceta) REFERENCES RECETA(NoReceta),

	CONSTRAINT FK_RECETAS_POR_CLIENTE_IdCliente
		FOREIGN KEY (IdCliente) REFERENCES CLIENTE(IdCliente)
)


; --*/