USE FARMATICA;

SELECT * FROM CLIENTE;
SELECT * FROM TELEFONOS_POR_CLIENTE; 
SELECT * FROM PADECIMIENTOS_POR_CLIENTE; 
SELECT * FROM DOCTOR;
SELECT * FROM SUCURSAL; 
SELECT * FROM MEDICAMENTO; 
SELECT * FROM MEDICAMENTO_EN_SUCURSAL; 
SELECT * FROM PEDIDO;
SELECT * FROM MEDICAMENTOS_POR_PEDIDO; 
SELECT * FROM RECETA; 
SELECT * FROM MEDICAMENTOS_POR_RECETA; 
SELECT * FROM EMPLEADO;
SELECT * FROM EMPRESA;
SELECT * FROM PEDIDO_FISICO;
SELECT * FROM MEDICAMENTOS_POR_PEDIDO_FISICO;